POST http://localhost:8080/accountsettings
Content-Type: application/json

{
  "userId": "urn:accountsettings:1",
  "firstname": "Christoph",
  "lastname": "Manig",
  "taxationType": "IST",
  "profitAssessment": "EUR"
}

###
PATCH http://localhost:8080/accountsettings
Content-Type: application/json

{
  "userId": "urn:accountsettings:1",
  "changes": {
      "firstname": "Till"
    }
}

###
PATCH http://localhost:8080/accountsettings
Content-Type: application/json

{
  "userId": "urn:accountsettings:1",
  "changes": {
      "lastname": "Helbing"
    }
}

###
PATCH http://localhost:8080/accountsettings
Content-Type: application/json

{
  "userId": "urn:accountsettings:1",
  "changes": {
      "taxationType": "SOLL"
    }
}

###
GET http://localhost:8080/accountsettings/urn:accountsettings:1
Content-Type: application/json
